// <auto-generated />
using CodeJam5b.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeJam5b.Server.Migrations
{
    [DbContext(typeof(CalorieCounterContext))]
    [Migration("20251211162317_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeJam5b.Models.Meal", b =>
                {
                    b.Property<string>("MealId")
                        .HasColumnType("text")
                        .HasColumnName("meal_id");

                    b.Property<int>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<int>("Carbs")
                        .HasColumnType("integer")
                        .HasColumnName("carbs");

                    b.Property<int>("Fat")
                        .HasColumnType("integer")
                        .HasColumnName("fat");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Protein")
                        .HasColumnType("integer")
                        .HasColumnName("protein");

                    b.HasKey("MealId");

                    b.ToTable("meals");
                });

            modelBuilder.Entity("CodeJam5b.Models.Progress", b =>
                {
                    b.Property<string>("ProgressId")
                        .HasColumnType("text")
                        .HasColumnName("progress_id");

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("integer")
                        .HasColumnName("current_weight");

                    b.Property<int>("TargetCals")
                        .HasColumnType("integer")
                        .HasColumnName("target_cals");

                    b.Property<int>("TargetCarbs")
                        .HasColumnType("integer")
                        .HasColumnName("target_carbs");

                    b.Property<int>("TargetFat")
                        .HasColumnType("integer")
                        .HasColumnName("target_fat");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("integer")
                        .HasColumnName("target_protein");

                    b.Property<int>("TargetWeight")
                        .HasColumnType("integer")
                        .HasColumnName("target_weight");

                    b.HasKey("ProgressId");

                    b.ToTable("progress");
                });
#pragma warning restore 612, 618
        }
    }
}
