// <auto-generated />
using CodeJam5b.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeJam5b.Server.Migrations
{
    [DbContext(typeof(CalorieCounterContext))]
    partial class CalorieCounterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeJam5b.Models.Meal", b =>
                {
                    b.Property<string>("MealId")
                        .HasColumnType("text")
                        .HasColumnName("meal_id");

                    b.Property<int>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<int>("Carbs")
                        .HasColumnType("integer")
                        .HasColumnName("carbs");

                    b.Property<int>("Fat")
                        .HasColumnType("integer")
                        .HasColumnName("fat");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Protein")
                        .HasColumnType("integer")
                        .HasColumnName("protein");

                    b.HasKey("MealId");

                    b.ToTable("meals");

                    b.HasData(
                        new
                        {
                            MealId = "1",
                            Calories = 350,
                            Carbs = 10,
                            Fat = 15,
                            MealName = "Chicken Salad",
                            Protein = 40
                        },
                        new
                        {
                            MealId = "2",
                            Calories = 450,
                            Carbs = 5,
                            Fat = 25,
                            MealName = "Grilled Salmon",
                            Protein = 50
                        },
                        new
                        {
                            MealId = "3",
                            Calories = 300,
                            Carbs = 50,
                            Fat = 10,
                            MealName = "Veggie Stir Fry",
                            Protein = 15
                        });
                });

            modelBuilder.Entity("CodeJam5b.Models.UserProgress", b =>
                {
                    b.Property<string>("ProgressId")
                        .HasColumnType("text")
                        .HasColumnName("progress_id");

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("integer")
                        .HasColumnName("current_weight");

                    b.Property<int>("TargetCals")
                        .HasColumnType("integer")
                        .HasColumnName("target_cals");

                    b.Property<int>("TargetCarbs")
                        .HasColumnType("integer")
                        .HasColumnName("target_carbs");

                    b.Property<int>("TargetFat")
                        .HasColumnType("integer")
                        .HasColumnName("target_fat");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("integer")
                        .HasColumnName("target_protein");

                    b.Property<int>("TargetWeight")
                        .HasColumnType("integer")
                        .HasColumnName("target_weight");

                    b.HasKey("ProgressId");

                    b.ToTable("progress");

                    b.HasData(
                        new
                        {
                            ProgressId = "1",
                            CurrentWeight = 180,
                            TargetCals = 2000,
                            TargetCarbs = 250,
                            TargetFat = 80,
                            TargetProtein = 160,
                            TargetWeight = 160
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
